INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (1,'frame1','analog1','Speicher 1 Oben');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (4,'frame1','analog2','Speicher 1 Unten');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (5,'frame1','analog3','Speicher 2 Oben');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (6,'frame1','analog4','Speicher 2 Unten');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (7,'frame1','analog5','Raum');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (8,'frame1','analog6','Außen');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (9,'frame1','analog7','VL Heizung Ist');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (10,'frame1','analog8','VL Fußboden Ist');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (11,'frame1','analog9','RL Warmwasser');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (12,'frame1','analog10','VL Heizung Soll');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (13,'frame1','analog11','VL Fußboden Soll');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (14,'frame1','analog12','Kessel');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (15,'frame1','analog13','Lade Temperatur');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (16,'frame1','analog14','RL Solar');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (17,'frame1','analog15','VL Röhrenkollektor');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (18,'frame1','analog16','VL Flachkollektor');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (19,'frame1','power1','Leistung Flachkollektor');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (20,'frame1','power2','Leistung Röhrenkollektor');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (21,'frame1','energy1','Flachkollektor');
INSERT INTO `t_names` (`id`,`frame`,`type`,`name`) VALUES (22,'frame1','energy2','Röhrenkollektor');
