ALTER TABLE `t_chartoptions`
CHANGE `id` `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
CHANGE `chard_id` `chard_id` INT(10) UNSIGNED NOT NULL;

ALTER TABLE `t_data_test`
CHANGE `id` `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
CHANGE `digital1` `digital1` BIT(1) NULL DEFAULT NULL,
CHANGE `digital2` `digital2` BIT(1) NULL DEFAULT NULL,
CHANGE `digital3` `digital3` BIT(1) NULL DEFAULT NULL,
CHANGE `digital4` `digital4` BIT(1) NULL DEFAULT NULL,
CHANGE `digital5` `digital5` BIT(1) NULL DEFAULT NULL,
CHANGE `digital6` `digital6` BIT(1) NULL DEFAULT NULL,
CHANGE `digital7` `digital7` BIT(1) NULL DEFAULT NULL,
CHANGE `digital8` `digital8` BIT(1) NULL DEFAULT NULL,
CHANGE `digital9` `digital9` BIT(1) NULL DEFAULT NULL,
CHANGE `digital10` `digital10` BIT(1) NULL DEFAULT NULL,
CHANGE `digital11` `digital11` BIT(1) NULL DEFAULT NULL,
CHANGE `digital12` `digital12` BIT(1) NULL DEFAULT NULL,
CHANGE `digital13` `digital13` BIT(1) NULL DEFAULT NULL,
CHANGE `digital14` `digital14` BIT(1) NULL DEFAULT NULL,
CHANGE `digital15` `digital15` BIT(1) NULL DEFAULT NULL,
CHANGE `digital16` `digital16` BIT(1) NULL DEFAULT NULL,
CHANGE `speed1` `speed1` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
CHANGE `speed2` `speed2` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
CHANGE `speed3` `speed3` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
CHANGE `speed4` `speed4` TINYINT(2) UNSIGNED NULL DEFAULT NULL;

ALTER TABLE `t_digital_counts`
CHANGE `id` `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
CHANGE `digital1` `digital1` SMALLINT(3) UNSIGNED NULL DEFAULT NULL,
CHANGE `digital2` `digital2` SMALLINT(3) UNSIGNED NULL DEFAULT NULL,
CHANGE `digital3` `digital3` SMALLINT(3) UNSIGNED NULL DEFAULT NULL,
CHANGE `digital4` `digital4` SMALLINT(3) UNSIGNED NULL DEFAULT NULL,
CHANGE `digital5` `digital5` SMALLINT(3) UNSIGNED NULL DEFAULT NULL,
CHANGE `digital6` `digital6` SMALLINT(3) UNSIGNED NULL DEFAULT NULL,
CHANGE `digital7` `digital7` SMALLINT(3) UNSIGNED NULL DEFAULT NULL,
CHANGE `digital8` `digital8` SMALLINT(3) UNSIGNED NULL DEFAULT NULL,
CHANGE `digital9` `digital9` SMALLINT(3) UNSIGNED NULL DEFAULT NULL,
CHANGE `digital10` `digital10` SMALLINT(3) UNSIGNED NULL DEFAULT NULL,
CHANGE `digital11` `digital11` SMALLINT(3) UNSIGNED NULL DEFAULT NULL,
CHANGE `digital12` `digital12` SMALLINT(3) UNSIGNED NULL DEFAULT NULL,
CHANGE `digital13` `digital13` SMALLINT(3) UNSIGNED NULL DEFAULT NULL,
CHANGE `digital14` `digital14` SMALLINT(3) UNSIGNED NULL DEFAULT NULL,
CHANGE `digital15` `digital15` SMALLINT(3) UNSIGNED NULL DEFAULT NULL,
CHANGE `digital16` `digital16` SMALLINT(3) UNSIGNED NULL DEFAULT NULL;

ALTER TABLE `t_digital_times`
CHANGE `id` `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE `t_energies`
CHANGE `id` `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE `t_max`
CHANGE `id` `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
CHANGE `speed1` `speed1` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
CHANGE `speed2` `speed2` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
CHANGE `speed3` `speed3` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
CHANGE `speed4` `speed4` TINYINT(2) UNSIGNED NULL DEFAULT NULL;

ALTER TABLE `t_menu`
CHANGE `id` `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
CHANGE `order` `order` TINYINT(3) UNSIGNED NULL DEFAULT NULL;

ALTER TABLE `t_min`
CHANGE `id` `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
CHANGE `speed1` `speed1` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
CHANGE `speed2` `speed2` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
CHANGE `speed3` `speed3` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
CHANGE `speed4` `speed4` TINYINT(2) UNSIGNED NULL DEFAULT NULL;

ALTER TABLE `t_names`
CHANGE `id` `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE `t_names_of_charts`
CHANGE `chart_id` `chart_id` INT(10) UNSIGNED NOT NULL,
CHANGE `order` `order` INT(10) UNSIGNED NULL DEFAULT NULL;

ALTER TABLE `t_schema`
CHANGE `id` `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE `t_users`
CHANGE `id` `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;
